//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerTell.PokerHandParsers.IntegrationTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerTell.PokerHandParsers.IntegrationTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerStars Game #41849120736: Tournament #257371180, $5.00+$0.50 USD Hold&apos;em No Limit - Level III (25/50) - 2010/03/28 16:41:22 ET
        ///Table &apos;257371180 5&apos; 9-max Seat #7 is the button
        ///Seat 1: renniweg (1225 in chips) 
        ///Seat 2: Rikardo1 (3780 in chips) 
        ///Seat 3: Zhycco (830 in chips) 
        ///Seat 5: troyfu (1525 in chips) 
        ///Seat 6: DGM3283 (1455 in chips) 
        ///Seat 7: themiskost (1440 in chips) 
        ///Seat 8: keechman (3345 in chips) 
        ///Seat 9: skizzott23 (4066 in chips) 
        ///keechman: posts small blind 25
        ///skizzott23: posts big [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PokerStars_RenniwegIsAllInPreflopAndWins1885 {
            get {
                return ResourceManager.GetString("PokerStars_RenniwegIsAllInPreflopAndWins1885", resourceCulture);
            }
        }
    }
}
