//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerTell.PokerHandParsers.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerTell.PokerHandParsers.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerStars Game #22525256705:  Holdem No Limit ($0.01/$0.02) - 2008/12/01 9:07:47 ET
        ///Table Chloris III 9-max Seat #1 is the button
        ///Seat 1: humaaa ($1.01 in chips)
        ///Seat 2: hobbyplayer ($8.40 in chips)
        ///Seat 3: Ares2k7 ($5 in chips)
        ///Seat 4: renniweg ($2.54 in chips)
        ///Seat 5: jumperstinks ($4.30 in chips)
        ///Seat 6: brandy9111 ($5.28 in chips)
        ///Seat 7: slbr ($2.42 in chips)
        ///Seat 8: DbLBbL ($0.45 in chips)
        ///Seat 9: DJ Landry ($5.37 in chips)
        ///hobbyplayer: posts small blind $0.01
        ///Ares2k7: posts big blind $0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PokerStars_PokerOfficeDatabaseBlob {
            get {
                return ResourceManager.GetString("PokerStars_PokerOfficeDatabaseBlob", resourceCulture);
            }
        }
    }
}
