//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerTell.User.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerTell.User.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AboutView_Author {
            get {
                return ResourceManager.GetString("AboutView_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string AboutView_Homepage {
            get {
                return ResourceManager.GetString("AboutView_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many thanks go to:.
        /// </summary>
        public static string AboutView_ThanksTo {
            get {
                return ResourceManager.GetString("AboutView_ThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutView_Title {
            get {
                return ResourceManager.GetString("AboutView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutView_Version {
            get {
                return ResourceManager.GetString("AboutView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are very sorry ...
        ///
        ///Something unexpected occurred, but you will be able to resume what you were doing.
        ///
        ///In the next dialog you&apos;ll get a chance to send us a short report, including any comments you may have.
        ///.
        /// </summary>
        public static string NonTerminatingUnhandledException_Message {
            get {
                return ResourceManager.GetString("NonTerminatingUnhandledException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Screenshot.
        /// </summary>
        public static string ReportView_IncludeScreenshot {
            get {
                return ResourceManager.GetString("ReportView_IncludeScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logfile Content.
        /// </summary>
        public static string ReportView_LogfileContent {
            get {
                return ResourceManager.GetString("ReportView_LogfileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add your comments about the problem that you encountered here.
        /// </summary>
        public static string ReportView_PleaseAddComments {
            get {
                return ResourceManager.GetString("ReportView_PleaseAddComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Content.
        /// </summary>
        public static string ReportView_ReportContent {
            get {
                return ResourceManager.GetString("ReportView_ReportContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string ReportView_Screenshot {
            get {
                return ResourceManager.GetString("ReportView_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerTell Report.
        /// </summary>
        public static string ReportView_Title {
            get {
                return ResourceManager.GetString("ReportView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        public static string Status_ConnectedTo {
            get {
                return ResourceManager.GetString("Status_ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing database.
        /// </summary>
        public static string StatusBarView_ImportingDatabase {
            get {
                return ResourceManager.GetString("StatusBarView_ImportingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing hand histories.
        /// </summary>
        public static string StatusBarView_ImportingHandHistories {
            get {
                return ResourceManager.GetString("StatusBarView_ImportingHandHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are very sorry ...
        ///
        ///Something unexpected occurred, and PokerTell will have to close.
        ///
        ///In the next dialog you&apos;ll get a chance to send us a short report, including any comments you may have..
        /// </summary>
        public static string TerminatingUnhandledException_Message {
            get {
                return ResourceManager.GetString("TerminatingUnhandledException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string User_MenuItem_About {
            get {
                return ResourceManager.GetString("User_MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Problem.
        /// </summary>
        public static string User_MenuItem_ReportAProblem {
            get {
                return ResourceManager.GetString("User_MenuItem_ReportAProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string User_MenuItem_Title {
            get {
                return ResourceManager.GetString("User_MenuItem_Title", resourceCulture);
            }
        }
    }
}
