//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4005
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerTell.DatabaseSetup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerTell.DatabaseSetup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ConfigureProviderView_Close {
            get {
                return ResourceManager.GetString("ConfigureProviderView_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string ConfigureProviderView_ConnectionSettings {
            get {
                return ResourceManager.GetString("ConfigureProviderView_ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        public static string ConfigureProviderView_Password {
            get {
                return ResourceManager.GetString("ConfigureProviderView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ConfigureProviderView_Save {
            get {
                return ResourceManager.GetString("ConfigureProviderView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: .
        /// </summary>
        public static string ConfigureProviderView_Server {
            get {
                return ResourceManager.GetString("ConfigureProviderView_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string ConfigureProviderView_TestConnection {
            get {
                return ResourceManager.GetString("ConfigureProviderView_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Defaults.
        /// </summary>
        public static string ConfigureProviderView_UseDefaults {
            get {
                return ResourceManager.GetString("ConfigureProviderView_UseDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use PokerOffice Settings.
        /// </summary>
        public static string ConfigureProviderView_UsePokerOfficeSettings {
            get {
                return ResourceManager.GetString("ConfigureProviderView_UsePokerOfficeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name: .
        /// </summary>
        public static string ConfigureProviderView_UserName {
            get {
                return ResourceManager.GetString("ConfigureProviderView_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure MySql Server.
        /// </summary>
        public static string DatabaseSetupMenu_ConfigureMySqlServer_Header {
            get {
                return ResourceManager.GetString("DatabaseSetupMenu_ConfigureMySqlServer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Setup.
        /// </summary>
        public static string DatabaseSetupMenu_Header {
            get {
                return ResourceManager.GetString("DatabaseSetupMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerTell was unable to connect to the server specified in the settings. 
        ///Please make sure the database server is running and check the Database Settings.
        ///Check that the servername, username and possibly password were entered correctly..
        /// </summary>
        public static string Error_UnableToConnectToServer {
            get {
                return ResourceManager.GetString("Error_UnableToConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found MySql {0}  installed on your computer..
        /// </summary>
        public static string Info_FoundMySqInstallation {
            get {
                return ResourceManager.GetString("Info_FoundMySqInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MySql installation found..
        /// </summary>
        public static string Info_MySqlInstallationNotFound {
            get {
                return ResourceManager.GetString("Info_MySqlInstallationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to the {0} server. Now you should create or choose a database to use with it..
        /// </summary>
        public static string Info_SuccessfullyConnectedToServer {
            get {
                return ResourceManager.GetString("Info_SuccessfullyConnectedToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS actionhhd;
        ///
        ///CREATE TABLE actionhhd (
        ///  playerid int(11) unsigned NOT NULL,
        ///  handid bigint(20) unsigned NOT NULL,
        ///  m int(10) unsigned DEFAULT NULL,
        ///  cards varchar(6) DEFAULT NULL,
        ///  position tinyint(2) DEFAULT NULL COMMENT &apos;Order of players acting on the hand (0-SB to TotalPlayers-1)&apos;,
        ///  strategicposition tinyint(2) DEFAULT NULL COMMENT &apos;Stratecic Position of player SB to BU&apos;,
        ///  inposflop tinyint(1) unsigned NOT NULL DEFAULT &apos;2&apos; COMMENT &apos;1=IP, 0=OOP 2=N/A(no action on Round)&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MySql_Queries_CreateTables {
            get {
                return ResourceManager.GetString("MySql_Queries_CreateTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE IF NOT EXISTS {0};.
        /// </summary>
        public static string Sql_Queries_CreateDatabase {
            get {
                return ResourceManager.GetString("Sql_Queries_CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP DATABASE IF EXISTS {0};.
        /// </summary>
        public static string Sql_Queries_DropDatabase {
            get {
                return ResourceManager.GetString("Sql_Queries_DropDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW DATABASES;.
        /// </summary>
        public static string Sql_Queries_ShowDatabases {
            get {
                return ResourceManager.GetString("Sql_Queries_ShowDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS actionhhd; 
        ///
        ///CREATE TABLE actionhhd(
        ///       playerid int(11) NOT NULL,
        ///       handid bigint(20) NOT NULL,
        ///       m int(10) DEFAULT NULL,
        ///       cards varchar(6) DEFAULT NULL,
        ///       position tinyint(2) DEFAULT NULL,
        ///       strategicposition tinyint(2) DEFAULT NULL,
        ///       inposflop tinyint(1) NOT NULL  default &apos;2&apos;,
        ///       inposturn tinyint(1) NOT NULL default &apos;2&apos;,
        ///       inposriver tinyint(1) NOT NULL default &apos;2&apos;,
        ///       raiseinfrontpreflopfrompos tinyint(2) NOT NULL default [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SQLite_Queries_CreateTables {
            get {
                return ResourceManager.GetString("SQLite_Queries_CreateTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database you are trying to create already exists.
        ///Therefore it could not be created.
        ///If you were trying to delete all its data, use Clear Database instead..
        /// </summary>
        public static string Warning_DatabaseExistsException {
            get {
                return ResourceManager.GetString("Warning_DatabaseExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerTell was unable to find a MySql installatin on your computer.\nIf you are sure it is installed enter the appropriate settings and test the connection. If still unsuccessful consider reinstalling the MySql server..
        /// </summary>
        public static string Warning_MySqlInstallationNotFound {
            get {
                return ResourceManager.GetString("Warning_MySqlInstallationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not using a MySQL Database in PokerOffice.Follow the help file instructions to install the MySQL Server and change to MySQL Database in PokerOffice..
        /// </summary>
        public static string Warning_MySqlNotUsedInPokerOffice {
            get {
                return ResourceManager.GetString("Warning_MySqlNotUsedInPokerOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find a PokerOffice installation. If you are sure it is installed carefully enter the values that you find in PokerOffice/Database/NetworkSettings..
        /// </summary>
        public static string Warning_PokerOfficeNotFound {
            get {
                return ResourceManager.GetString("Warning_PokerOfficeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerTell was unable to connect to the Database specified in the settings. 
        ///Please make sure the MySql Server is running and check the Database Settings using the Database Menu.
        ///Check that the hostname, username, password were entered correctly and that you chose an existing database or created one..
        /// </summary>
        public static string Warning_UnableToConnectToDatabase {
            get {
                return ResourceManager.GetString("Warning_UnableToConnectToDatabase", resourceCulture);
            }
        }
    }
}
