/*
Created by SharpDevelop.
 * Thorsten Lorenz
 * Date: 1/19/2009
 * Time: 7:57 PM
 */

using System;
using System.Runtime.InteropServices;
namespace DllWrappers
{
	/// <summary>
	/// Wrapper for CallWindowProc.
	/// </summary>
	public partial class User32
	{
		/// <summary> The RegisterHotKey function defines a system-wide hot key </summary>
		/// /// <param name="hwnd">Handle to the window that will receive WM_HOTKEY messages
		/// /// generated by the hot key.</param>
		/// /// <param name="id">Specifies the identifier of the hot key.</param>
		/// /// <param name="fsModifiers">Specifies keys that must be pressed in combination with the key
		/// /// specified by the 'vk' parameter in order to generate the WM_HOTKEY message.</param>
		/// /// <param name="vk">Specifies the virtual-key code of the hot key</param>
		/// /// <returns><c>true</c> if the function succeeds, otherwise <c>false</c></returns>
		/// /// <seealso cref="http://msdn.microsoft.com/en-us/library/ms646309(VS.85).aspx"/>
		 [DllImport("user32.dll")]
		 [return: MarshalAs(UnmanagedType.Bool)]
		 static extern bool RegisterHotKey(IntPtr hWnd, int id, uint fsModifiers,
		   uint vk);
		
		 
		
	}
	
}