//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4005
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerTell.LiveTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerTell.LiveTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Poker Rooms whose Hand History Directories have been added.
        /// </summary>
        public static string AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereDetected {
            get {
                return ResourceManager.GetString("AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a Poker Room installed and it is not shown here, first make sure that PokerTell supports it by following the link below.
        ///You may then add its Hand History Folder manually inside the Advanced section..
        /// </summary>
        public static string AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereDetectedInformation {
            get {
                return ResourceManager.GetString("AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereDetectedInform" +
                        "ation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Poker Rooms whose Hand History Directories could not be detected.
        /// </summary>
        public static string AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereNotDetected {
            get {
                return ResourceManager.GetString("AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of automatic Hand History folders detection.
        /// </summary>
        public static string AutoDetectHandHistoryFoldersResultsView_Title {
            get {
                return ResourceManager.GetString("AutoDetectHandHistoryFoldersResultsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are sure that {0} is configured to save your Hand Histories to a folder on disk, add that folder manually inside the Advanced section.
        ///Otherwise follow the link below to get instructions on how to configure {0} correctly..
        /// </summary>
        public static string AutoDetectHandHistoryFoldersResultsViewModel_RoomWhoseHandHistoryFolderWasNotDetectedInformation {
            get {
                return ResourceManager.GetString("AutoDetectHandHistoryFoldersResultsViewModel_RoomWhoseHandHistoryFolderWasNotDete" +
                        "ctedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LiveTracker_MenuItem_Settings {
            get {
                return ResourceManager.GetString("LiveTracker_MenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Tracker.
        /// </summary>
        public static string LiveTracker_MenuItem_Title {
            get {
                return ResourceManager.GetString("LiveTracker_MenuItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Hand History.
        /// </summary>
        public static string LiveTracker_MenuItem_TrackHandHistory {
            get {
                return ResourceManager.GetString("LiveTracker_MenuItem_TrackHandHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add HandHistory Folder.
        /// </summary>
        public static string LiveTrackerSettingsView_AddHandHistoryFolder {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_AddHandHistoryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Detect Handhistory Folders.
        /// </summary>
        public static string LiveTrackerSettingsView_AutoDetectHandHistoryFolders {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_AutoDetectHandHistoryFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Autotracking.
        /// </summary>
        public static string LiveTrackerSettingsView_AutoTrack {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_AutoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show LiveStats Window on Startup.
        /// </summary>
        public static string LiveTrackerSettingsView_Show_LiveStatsWindowOnStartup {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_Show_LiveStatsWindowOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show mucked Cards.
        /// </summary>
        public static string LiveTrackerSettingsView_Show_MuckedCards {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_Show_MuckedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my Statistics.
        /// </summary>
        public static string LiveTrackerSettingsView_Show_MyStatistics {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_Show_MyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Table Overlay.
        /// </summary>
        public static string LiveTrackerSettingsView_Show_TableOverlay {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_Show_TableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveTracker Settings.
        /// </summary>
        public static string LiveTrackerSettingsView_Title {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hand histories in file &quot;{0}&quot; are being tracked already..
        /// </summary>
        public static string Warning_HandHistoriesAreTrackedAlready {
            get {
                return ResourceManager.GetString("Warning_HandHistoriesAreTrackedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you are trying to add is already in the list of tracked folders..
        /// </summary>
        public static string Warning_HandHistoryFolderIsTrackedAlready {
            get {
                return ResourceManager.GetString("Warning_HandHistoryFolderIsTrackedAlready", resourceCulture);
            }
        }
    }
}
