//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerTell.LiveTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerTell.LiveTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Poker Rooms whose Hand History Directories have been added.
        /// </summary>
        public static string AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereDetected {
            get {
                return ResourceManager.GetString("AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a Poker Room installed and it is not shown here, first make sure that PokerTell supports it by following the link below.
        ///You may then add its Hand History Folder manually inside the Advanced section..
        /// </summary>
        public static string AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereDetectedInformation {
            get {
                return ResourceManager.GetString("AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereDetectedInform" +
                        "ation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Poker Rooms whose Hand History Directories could not be detected.
        /// </summary>
        public static string AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereNotDetected {
            get {
                return ResourceManager.GetString("AutoDetectHandHistoryFoldersResultsView_RoomsWhoseHandHistoriesWereNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of automatic Hand History folders detection.
        /// </summary>
        public static string AutoDetectHandHistoryFoldersResultsView_Title {
            get {
                return ResourceManager.GetString("AutoDetectHandHistoryFoldersResultsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are sure that {0} is configured to save your Hand Histories to a folder on disk, add that folder manually inside the Advanced section.
        ///Otherwise follow the link below to get instructions on how to configure {0} correctly..
        /// </summary>
        public static string AutoDetectHandHistoryFoldersResultsViewModel_RoomWhoseHandHistoryFolderWasNotDetectedInformation {
            get {
                return ResourceManager.GetString("AutoDetectHandHistoryFoldersResultsViewModel_RoomWhoseHandHistoryFolderWasNotDete" +
                        "ctedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Layouts&gt;
        ///  &lt;Layout TotalSeats=&quot;2&quot;&gt;
        ///    &lt;ShowPreFlop&gt;true&lt;/ShowPreFlop&gt;
        ///    &lt;ShowFlop&gt;true&lt;/ShowFlop&gt;
        ///    &lt;ShowTurn&gt;false&lt;/ShowTurn&gt;
        ///    &lt;ShowRiver&gt;false&lt;/ShowRiver&gt;
        ///    &lt;ShowHarringtonM&gt;true&lt;/ShowHarringtonM&gt;
        ///    &lt;StatisticsPanelWidth&gt;121.2365591397849&lt;/StatisticsPanelWidth&gt;
        ///    &lt;StatisticsPanelHeight&gt;33.97849462365582&lt;/StatisticsPanelHeight&gt;
        ///    &lt;Background&gt;#170000FF&lt;/Background&gt;
        ///    &lt;OutOfPositionForeground&gt;#FFFFFFFF&lt;/OutOfPositionForeground&gt;
        ///    &lt;InPosi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FullTiltPokerLayout {
            get {
                return ResourceManager.GetString("FullTiltPokerLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preferred seats of the following Poker sites have been configured:.
        /// </summary>
        public static string Info_PreferredSeatsHaveBeenConfigured {
            get {
                return ResourceManager.GetString("Info_PreferredSeatsHaveBeenConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LiveTracker_MenuItem_Settings {
            get {
                return ResourceManager.GetString("LiveTracker_MenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Tracker.
        /// </summary>
        public static string LiveTracker_MenuItem_Title {
            get {
                return ResourceManager.GetString("LiveTracker_MenuItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Hand History.
        /// </summary>
        public static string LiveTracker_MenuItem_TrackHandHistory {
            get {
                return ResourceManager.GetString("LiveTracker_MenuItem_TrackHandHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add HandHistory Folder.
        /// </summary>
        public static string LiveTrackerSettingsView_AddHandHistoryFolder {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_AddHandHistoryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Detect Handhistory Folders.
        /// </summary>
        public static string LiveTrackerSettingsView_AutoDetectHandHistoryFolders {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_AutoDetectHandHistoryFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect preferred seats.
        /// </summary>
        public static string LiveTrackerSettingsView_AutoDetectPreferredSeats {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_AutoDetectPreferredSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Autotracking.
        /// </summary>
        public static string LiveTrackerSettingsView_AutoTrack {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_AutoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show LiveStats Window on Startup.
        /// </summary>
        public static string LiveTrackerSettingsView_Show_LiveStatsWindowOnStartup {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_Show_LiveStatsWindowOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show mucked Cards.
        /// </summary>
        public static string LiveTrackerSettingsView_Show_MuckedCards {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_Show_MuckedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my Statistics.
        /// </summary>
        public static string LiveTrackerSettingsView_Show_MyStatistics {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_Show_MyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Table Overlay.
        /// </summary>
        public static string LiveTrackerSettingsView_Show_TableOverlay {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_Show_TableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveTracker Settings.
        /// </summary>
        public static string LiveTrackerSettingsView_Title {
            get {
                return ResourceManager.GetString("LiveTrackerSettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop in.
        /// </summary>
        public static string OverlayDetailsView_ToolTip_Popin {
            get {
                return ResourceManager.GetString("OverlayDetailsView_ToolTip_Popin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop out.
        /// </summary>
        public static string OverlayDetailsView_ToolTip_Popout {
            get {
                return ResourceManager.GetString("OverlayDetailsView_ToolTip_Popout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Layouts&gt;
        ///  &lt;Layout TotalSeats=&quot;2&quot;&gt;
        ///    &lt;ShowPreFlop&gt;true&lt;/ShowPreFlop&gt;
        ///    &lt;ShowFlop&gt;true&lt;/ShowFlop&gt;
        ///    &lt;ShowTurn&gt;false&lt;/ShowTurn&gt;
        ///    &lt;ShowRiver&gt;false&lt;/ShowRiver&gt;
        ///    &lt;ShowHarringtonM&gt;true&lt;/ShowHarringtonM&gt;
        ///    &lt;StatisticsPanelWidth&gt;121.2365591397849&lt;/StatisticsPanelWidth&gt;
        ///    &lt;StatisticsPanelHeight&gt;33.97849462365582&lt;/StatisticsPanelHeight&gt;
        ///    &lt;Background&gt;#170000FF&lt;/Background&gt;
        ///    &lt;OutOfPositionForeground&gt;#FFFFFFFF&lt;/OutOfPositionForeground&gt;
        ///    &lt;InPosi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PokerStarsLayout {
            get {
                return ResourceManager.GetString("PokerStarsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Hands.
        /// </summary>
        public static string TableStatisticsView_BrowseAllHandsOfSelectedPlayer {
            get {
                return ResourceManager.GetString("TableStatisticsView_BrowseAllHandsOfSelectedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse all hands of the selected player.
        /// </summary>
        public static string TableStatisticsView_BrowseAllHandsOfSelectedPlayer_ToolTip {
            get {
                return ResourceManager.GetString("TableStatisticsView_BrowseAllHandsOfSelectedPlayer_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string TableStatisticsView_Filter {
            get {
                return ResourceManager.GetString("TableStatisticsView_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter all hands of the selected player.
        /// </summary>
        public static string TableStatisticsView_Filter_ToolTip {
            get {
                return ResourceManager.GetString("TableStatisticsView_Filter_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigator.
        /// </summary>
        public static string TableStatisticsView_Investigator {
            get {
                return ResourceManager.GetString("TableStatisticsView_Investigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string TableStatisticsView_Players {
            get {
                return ResourceManager.GetString("TableStatisticsView_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handhistories.
        /// </summary>
        public static string TrackHandHistoryDialog_Handhistories {
            get {
                return ResourceManager.GetString("TrackHandHistoryDialog_Handhistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Hand History.
        /// </summary>
        public static string TrackHandHistoryDialog_Title {
            get {
                return ResourceManager.GetString("TrackHandHistoryDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hand histories in file &quot;{0}&quot; are being tracked already..
        /// </summary>
        public static string Warning_HandHistoriesAreTrackedAlready {
            get {
                return ResourceManager.GetString("Warning_HandHistoriesAreTrackedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you are trying to add is already in the list of tracked folders..
        /// </summary>
        public static string Warning_HandHistoryFolderIsTrackedAlready {
            get {
                return ResourceManager.GetString("Warning_HandHistoryFolderIsTrackedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately PokerTel couldn&apos;t find a Poker Room installed on your computer that uses preferred seat settings and allows them to be saved..
        /// </summary>
        public static string Warning_NoPreferredSeatsCouldBeConfigured {
            get {
                return ResourceManager.GetString("Warning_NoPreferredSeatsCouldBeConfigured", resourceCulture);
            }
        }
    }
}
