//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4005
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerTell.PokerHand.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerTell.PokerHand.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the big blind.
        /// </summary>
        public static string BB {
            get {
                return ResourceManager.GetString("BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the button.
        /// </summary>
        public static string BU {
            get {
                return ResourceManager.GetString("BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the cutoff seat.
        /// </summary>
        public static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to early position.
        /// </summary>
        public static string EA {
            get {
                return ResourceManager.GetString("EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string HandHistoryView_Cards_Header {
            get {
                return ResourceManager.GetString("HandHistoryView_Cards_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s HoleCards.
        /// </summary>
        public static string HandHistoryView_Cards_ToolTip {
            get {
                return ResourceManager.GetString("HandHistoryView_Cards_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop.
        /// </summary>
        public static string HandHistoryView_Flop_Header {
            get {
                return ResourceManager.GetString("HandHistoryView_Flop_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Actions.
        /// </summary>
        public static string HandHistoryView_Flop_ToolTip {
            get {
                return ResourceManager.GetString("HandHistoryView_Flop_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string HandHistoryView_M_Header {
            get {
                return ResourceManager.GetString("HandHistoryView_M_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s M at start of hand.
        /// </summary>
        public static string HandHistoryView_M_ToolTip {
            get {
                return ResourceManager.GetString("HandHistoryView_M_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HandHistoryView_PlayerName_Header {
            get {
                return ResourceManager.GetString("HandHistoryView_PlayerName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Player.
        /// </summary>
        public static string HandHistoryView_PlayerName_ToolTip {
            get {
                return ResourceManager.GetString("HandHistoryView_PlayerName_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        public static string HandHistoryView_Position_Header {
            get {
                return ResourceManager.GetString("HandHistoryView_Position_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s Position.
        /// </summary>
        public static string HandHistoryView_Position_ToolTip {
            get {
                return ResourceManager.GetString("HandHistoryView_Position_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preflop.
        /// </summary>
        public static string HandHistoryView_Preflop_Header {
            get {
                return ResourceManager.GetString("HandHistoryView_Preflop_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preflop Actions.
        /// </summary>
        public static string HandHistoryView_Preflop_ToolTip {
            get {
                return ResourceManager.GetString("HandHistoryView_Preflop_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River.
        /// </summary>
        public static string HandHistoryView_River_Header {
            get {
                return ResourceManager.GetString("HandHistoryView_River_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Actions.
        /// </summary>
        public static string HandHistoryView_River_ToolTip {
            get {
                return ResourceManager.GetString("HandHistoryView_River_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        public static string HandHistoryView_Turn_Header {
            get {
                return ResourceManager.GetString("HandHistoryView_Turn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Actions.
        /// </summary>
        public static string HandHistoryView_Turn_ToolTip {
            get {
                return ResourceManager.GetString("HandHistoryView_Turn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to late position.
        /// </summary>
        public static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middle position.
        /// </summary>
        public static string MI {
            get {
                return ResourceManager.GetString("MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the small blind.
        /// </summary>
        public static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
    }
}
