//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4005
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerTell.SessionReview.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerTell.SessionReview.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create _Report.
        /// </summary>
        internal static string SessionReviewMenuItem_Create_Report {
            get {
                return ResourceManager.GetString("SessionReviewMenuItem_Create_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import Hand Histories.
        /// </summary>
        internal static string SessionReviewMenuItem_Import_Hand_Histories {
            get {
                return ResourceManager.GetString("SessionReviewMenuItem_Import_Hand_Histories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open Review.
        /// </summary>
        internal static string SessionReviewMenuItem_Open_Review {
            get {
                return ResourceManager.GetString("SessionReviewMenuItem_Open_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Report.
        /// </summary>
        internal static string SessionReviewMenuItem_Save_Report {
            get {
                return ResourceManager.GetString("SessionReviewMenuItem_Save_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Review.
        /// </summary>
        internal static string SessionReviewMenuItem_Save_Review {
            get {
                return ResourceManager.GetString("SessionReviewMenuItem_Save_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Review.
        /// </summary>
        internal static string SessionReviewMenuItem_Title {
            get {
                return ResourceManager.GetString("SessionReviewMenuItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to club.gif.
        /// </summary>
        internal static string Url_Suits_Club {
            get {
                return ResourceManager.GetString("Url_Suits_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diamond.gif.
        /// </summary>
        internal static string Url_Suits_Diamond {
            get {
                return ResourceManager.GetString("Url_Suits_Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heart.gif.
        /// </summary>
        internal static string Url_Suits_Heart {
            get {
                return ResourceManager.GetString("Url_Suits_Heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.flopturnriver.com/phpBB2/images/smiles/.
        /// </summary>
        internal static string Url_Suits_Path {
            get {
                return ResourceManager.GetString("Url_Suits_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spade.gif.
        /// </summary>
        internal static string Url_Suits_Spade {
            get {
                return ResourceManager.GetString("Url_Suits_Spade", resourceCulture);
            }
        }
    }
}
