//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4005
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerTell.Statistics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerTell.Statistics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter.
        /// </summary>
        public static string FilterAdjustment_ApplyFilter {
            get {
                return ResourceManager.GetString("FilterAdjustment_ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter to all.
        /// </summary>
        public static string FilterAdjustment_ApplyFilterToAll {
            get {
                return ResourceManager.GetString("FilterAdjustment_ApplyFilterToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for .
        /// </summary>
        public static string FilterAdjustment_FilterFor {
            get {
                return ResourceManager.GetString("FilterAdjustment_FilterFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Hands.
        /// </summary>
        public static string InvestigatorView_BrowseHands {
            get {
                return ResourceManager.GetString("InvestigatorView_BrowseHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cards.
        /// </summary>
        public static string InvestigatorView_InvestigateHoleCards {
            get {
                return ResourceManager.GetString("InvestigatorView_InvestigateHoleCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowRaise.
        /// </summary>
        public static string InvestigatorView_ShowRaise {
            get {
                return ResourceManager.GetString("InvestigatorView_ShowRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize Hands.
        /// </summary>
        public static string InvestigatorView_VisualizeHands {
            get {
                return ResourceManager.GetString("InvestigatorView_VisualizeHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check or Bet.
        /// </summary>
        public static string StatisticsSets_CheckOrBet {
            get {
                return ResourceManager.GetString("StatisticsSets_CheckOrBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check then React.
        /// </summary>
        public static string StatisticsSets_CheckThenReact {
            get {
                return ResourceManager.GetString("StatisticsSets_CheckThenReact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to React to Bet.
        /// </summary>
        public static string StatisticsSets_ReactToBet {
            get {
                return ResourceManager.GetString("StatisticsSets_ReactToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count.
        /// </summary>
        public static string StatisticsSets_TotalCount {
            get {
                return ResourceManager.GetString("StatisticsSets_TotalCount", resourceCulture);
            }
        }
    }
}
